### PR TITLE
66 mentor registration

### PR DESCRIPTION
**Pull request by sharifyy**

### CODE REVIEW

**Review by m-tilab — COMMENTED** [review]
Can you add a test case for invalid interviewTypeIds, please?
Also in case of an invalid LinkedIn URL? I mean we can check the URL pattern https://www.linkedin.com/in/{blob blob blob}

**Comment by sharifyy** [comment]
Dear @m-tilab Requested changes has been applied. Please review one more time

**Review by m-tilab — COMMENTED** [review]
If we have a duplicated email address in active accounts, we still register that should be prevent it

**Comment by m-tilab** [comment]
Properties of "detailsOfExpertise" and "linkedInUrl" in the request are optional and are based on requirement. If I don't send "detailsOfExpertise" and "linkedInUrl", I am getting null in the response. I think its better to prevent it and only respond properties that have a value instead of  presenting "null"

image

**Review by m-tilab — APPROVED** [review]

**Pull request merged**
